"""Thirty classic puzzle variants, retold with explicit assumptions."""

def puzzle(title, category, level, prompt, options, answer, hints, explanation):
    return dict(title=title, category=category, level=level, prompt=prompt,
                options=options, answer=answer, hints=hints, explanation=explanation)

PUZZLES = [
puzzle('The two doors','Deduction','Starter',
'Two doors lead to freedom and danger. Two guards know which is which. One always tells the truth; the other always lies. You may ask either guard one yes-or-no question. Which strategy guarantees freedom?',
['Ask whether the guard is truthful, then choose their door.','Ask whether the other guard would say the left door leads to freedom. If yes, take the right; if no, take the left.','Ask whether the left door leads to freedom and follow the answer.','Ask whether both doors are safe.'],1,
['Your question must work regardless of which guard you choose.','Nest one guard’s answer inside the other guard’s answer.'],
'If the left door is safe, the liar would say no and the truth-teller reports that no; the liar also lies about the truth-teller’s yes. Either guard answers no. If the left is dangerous, both answer yes. Therefore reverse the reported recommendation.'),
puzzle('Knights and knaves','Deduction','Starter',
'Every islander is either a knight who always tells the truth or a knave who always lies. A says, “We are both knaves.” B says nothing. What are they?',
['A is a knight; B is a knave.','Both are knights.','A is a knave; B is a knight.','Both are knaves.'],2,
['Could a knight truthfully say that both are knaves?','Once A is a knave, A’s whole statement must be false.'],
'A cannot be a knight, because the statement would then falsely call A a knave. A is a knave, so “both are knaves” is false. Since A is already a knave, B must be a knight.'),
puzzle('The mislabeled boxes','Deduction','Starter',
'Three boxes contain only apples, only oranges, and a mixture of both. Their labels are Apples, Oranges, and Mixed, but every label is wrong. You can draw one fruit without looking into a box. Which box should you draw from to identify all three?',
['Apples','Oranges','Mixed','One draw cannot be enough'],2,
['The box labeled Mixed cannot contain a mixture.','One fruit identifies that box completely; use the remaining wrong labels.'],
'Draw from Mixed. If it yields an apple, that box is Apples. The box labeled Oranges cannot be Oranges and cannot be the already identified Apples, so it is Mixed; the last is Oranges. The orange case is symmetric.'),
puzzle('Three switches','Deduction','Starter',
'Three switches outside a closed room control three incandescent bulbs inside, one switch per bulb. All bulbs start off and cold. You may operate switches, then enter the room only once. You may safely detect residual warmth. How can you match all three?',
['Turn on all three before entering.','Turn on one switch and enter immediately.','Toggle all three rapidly.','Leave A on for a while, turn A off, turn B on, then enter.'],3,
['A bulb has more than two observable states.','A recently switched-off incandescent bulb retains heat.'],
'B controls the lit bulb. A controls the unlit but warm bulb. C controls the unlit and cold bulb. This depends on heat-retaining bulbs and enough time for A to warm up.'),
puzzle('Wolf, goat, cabbage','Strategy','Starter',
'A farmer must ferry a wolf, a goat, and a cabbage across a river. The boat holds the farmer plus one item; only the farmer rows. Without the farmer, the wolf eats the goat and the goat eats the cabbage. What is the minimum number of one-way crossings?',
['5','7','9','It is impossible'],1,
['The goat must cross first.','You will have to bring the goat back once.'],
'Take goat across; return alone; take wolf across; bring goat back; take cabbage across; return alone; take goat across. That is 7. A five-crossing solution would require three deliveries with only empty returns, but after the second delivery an unsafe pair would be left on the far bank.'),
puzzle('The bridge at night','Strategy','Intermediate',
'Four people take 1, 2, 5, and 10 minutes to cross a bridge. At most two cross together, at the slower person’s speed. Every crossing requires the single torch, which must be carried back when needed. What is the minimum total time for everyone to cross?',
['15 minutes','17 minutes','19 minutes','21 minutes'],1,
['Do not make the fastest person escort everyone separately.','Send the two slowest people together.'],
'1 and 2 cross (2); 1 returns (1); 5 and 10 cross (10); 2 returns (2); 1 and 2 cross (2). Total: 17. The standard two ways to transfer the two slowest cost min(1 + 2×2 + 10, 2×1 + 5 + 10) = 15; crossing the remaining fastest pair costs 2.'),
puzzle('The poisoned bottle','Information','Intermediate',
'Exactly one of 1,000 bottles is poisoned. A test strip turns positive after exactly 24 hours if any poison touches it. You can put drops from multiple bottles on each strip, but have time for only one test round. What is the fewest strips that guarantees identifying the bottle?',
['10','32','500','999'],0,
['Each strip supplies one bit: positive or negative.','How many patterns do k binary results encode?'],
'Nine strips produce at most 2⁹ = 512 patterns, which is too few. Ten produce 1,024. Assign each bottle a distinct ten-bit label and test it on the strips corresponding to its 1 bits. The positive-strip pattern identifies the poisoned bottle, including an all-zero label if used.'),
puzzle('Nine coins','Information','Starter',
'Nine identical-looking coins include exactly one heavier counterfeit. Using a balance scale with no weights, how many weighings suffice in the worst case?',
['1','2','3','4'],1,
['A balance scale has three possible outcomes.','Divide the coins into three groups of three.'],
'Weigh three against three. An imbalance identifies the heavier group; a balance identifies the unweighed group. From those three, weigh one against one. The heavier coin, or the third if balanced, is the counterfeit. One weighing cannot distinguish nine possibilities.'),
puzzle('Twelve coins: information limit','Information','Intermediate',
'One of 12 coins is counterfeit and may be heavier or lighter. You must identify both the coin and whether it is heavy or light. What is the smallest k for which the counting bound 3ᵏ ≥ the number of possibilities holds? This question asks only for the information lower bound.',
['2','3','4','12'],1,
['Each coin gives two counterfeit possibilities.','Compare 24 with powers of three.'],
'There are 12 × 2 = 24 possibilities. Two weighings yield at most 9 outcome sequences; three yield at most 27. Thus k = 3. Counting alone does not construct a weighing strategy or prove attainability.'),
puzzle('Monty Hall','Probability','Intermediate',
'A car is placed uniformly behind one of three doors. You choose one. A host who knows the location always opens another door showing a goat, then always offers a switch. When two goat doors are available, the host chooses randomly. What is your chance of winning if you always switch?',
['1/3','1/2','2/3','1'],2,
['Switching wins exactly when your original choice was wrong.','Your first choice is wrong two times out of three.'],
'Your original choice wins with probability 1/3. The host always removes a goat. If your original choice was wrong (probability 2/3), the other unopened door holds the car. Always switching therefore wins with probability 2/3.'),
puzzle('Two children','Probability','Intermediate',
'A family is sampled uniformly from all two-child families with at least one boy. Assume each child is independently equally likely to be a boy or girl. What is the probability that both are boys?',
['1/4','1/3','1/2','2/3'],1,
['Write ordered outcomes using older and younger child.','Remove only the girl-girl outcome.'],
'The equally likely ordered outcomes BB, BG, GB, GG reduce to BB, BG, GB under the stated sampling rule. Only BB qualifies, so the probability is 1/3. A different way of selecting or reporting a child could change the answer.'),
puzzle('The birthday threshold','Probability','Intermediate',
'Assume independent birthdays uniformly distributed across 365 days, ignoring leap years. What is the smallest group with a probability greater than 50% that at least two people share a birthday?',
['23','30','183','366'],0,
['It is easier to calculate the probability that all birthdays differ.','Multiply 365/365 × 364/365 × … for the group.'],
'The no-match probability for n people is the product of (365−i)/365 for i from 0 to n−1. At n = 22, the match probability is about 47.57%; at n = 23 it is about 50.73%. Thus 23 is the first group size above 50%.'),
puzzle('The missing dollar','Arithmetic','Starter',
'Three guests pay $30. The actual room cost is $25; a porter returns $1 to each guest and keeps $2. The guests paid $27 net. Someone adds the porter’s $2 to get $29. Where is the missing dollar?',
['The hotel has it.','The porter kept $3.','There is no missing dollar; the $2 is already included in $27.','Each guest should receive another $1.'],2,
['Track where the net $27 went.','The amounts being added overlap.'],
'The $27 net payment is $25 for the hotel plus $2 for the porter. Adding $2 again double-counts it. The original $30 equals $25 + $2 + $3 returned to the guests.'),
puzzle('The bat and ball','Arithmetic','Starter',
'A bat and a ball cost $1.10 together. The bat costs exactly $1.00 more than the ball. How much does the ball cost?',
['$0.10','$0.05','$0.01','$0.15'],1,
['A ten-cent ball would imply a $1.10 bat.','Let the ball cost x cents: x + (x + 100) = 110.'],
'2x + 100 = 110 gives x = 5 cents. The bat costs $1.05 and the ball $0.05, totaling $1.10 with a $1 difference.'),
puzzle('The lily pond','Arithmetic','Starter',
'A patch of lilies doubles its area every day and exactly covers a pond on day 48. On which day did it cover half the pond?',
['Day 24','Day 46','Day 47','Day 12'],2,
['Work backward one day.','The previous day has half the area, not half the elapsed time.'],
'Because the covered area doubles from one day to the next, it is half full on day 47 and full on day 48.'),
puzzle('The climbing snail','Arithmetic','Starter',
'A snail starts at the bottom of a 10-metre well. Each day it climbs 3 metres; each night, if still in the well, it slides down 2 metres. On which day does it first escape?',
['Day 7','Day 8','Day 9','Day 10'],1,
['The snail does not slide back after reaching the rim.','At the start of day n, it has gained n−1 metres.'],
'After seven complete day-night cycles it is at 7 metres. On day 8 it climbs to 10 metres and escapes before another slide.'),
puzzle('Two burning ropes','Strategy','Intermediate',
'Two ropes each take exactly 60 minutes to burn from one end, but burn at irregular rates along their lengths. You can light ends simultaneously and observe when a rope finishes. How can you measure exactly 45 minutes?',
['Burn three quarters of one rope.','Light both ends of both ropes.','Light both ends of A and one end of B; when A finishes, light B’s other end.','Cut a rope in half and burn one half.'],2,
['Lighting both ends halves the total burn time, even with irregular rates.','After 30 minutes, B has 30 minutes of one-ended burn time left.'],
'A finishes in 30 minutes. B then has 30 minutes of one-ended burning remaining. Lighting B’s other end consumes that remainder in 15 minutes, for a total of 45. Length fractions alone do not measure time.'),
puzzle('The water jugs','Strategy','Intermediate',
'You have unmarked 3-litre and 5-litre jugs, unlimited water, and a drain. A move fills a jug, empties a jug, or pours until the source is empty or the destination full. Which sequence leaves exactly 4 litres in the 5-litre jug?',
['Fill 5; pour into 3; empty 3; pour 5 into 3; fill 5; pour into 3.','Fill 3; pour into 5; fill 3; pour into 5.','Fill 5; pour into 3; empty 5.','Fill both, then empty 3.'],0,
['First create a 2-litre amount.','A 3-litre jug holding 2 litres has space for exactly 1 litre.'],
'The states (3-jug, 5-jug) are (0,5), (3,2), (0,2), (2,0), (2,5), (3,4). The final pour removes exactly 1 litre from the full 5-litre jug.'),
puzzle('The hundred lockers','Patterns','Intermediate',
'100 lockers start closed. On pass k, you toggle every locker whose number is a multiple of k, for k = 1 through 100. How many lockers end open?',
['10','25','50','100'],0,
['Locker n is toggled once per positive divisor of n.','Divisors pair up, except at a square root.'],
'A locker ends open exactly when its number has an odd number of divisors. Only perfect squares have an unpaired divisor, their square root. The open lockers are 1² through 10², so there are 10.'),
puzzle('The mutilated chessboard','Patterns','Intermediate',
'Remove two diagonally opposite corner squares from an 8 × 8 chessboard. Can the remaining board be tiled with 31 dominoes, each covering two edge-adjacent squares?',
['Yes, by tiling row by row.','Yes, if some dominoes are vertical.','No, because the board has unequal numbers of black and white squares.','No, because 62 is odd.'],2,
['Color the board in the usual alternating pattern.','Every domino covers one square of each color.'],
'Opposite corners of an 8 × 8 board have the same color. Removing them leaves 30 squares of one color and 32 of the other. Every domino covers one of each, so tiling is impossible.'),
puzzle('The handshake party','Patterns','Starter',
'Six people attend a party. Each pair shakes hands exactly once. How many handshakes occur?',
['12','15','30','36'],1,
['Each person shakes hands with five others.','Counting from each person counts every handshake twice.'],
'There are 6 × 5 / 2 = 15 unordered pairs. Each pair contributes one handshake.'),
puzzle('Socks in the dark','Deduction','Starter',
'A drawer contains 10 red socks and 10 blue socks. You cannot see or feel their colors and draw without replacement. What is the smallest number that guarantees a matching-color pair?',
['2','3','10','11'],1,
['Think about the worst possible first two draws.','There are only two colors.'],
'Two socks might have different colors. The third must match one of them, by the pigeonhole principle. Thus three are necessary and sufficient.'),
puzzle('The last stone','Strategy','Intermediate',
'A pile has 21 stones. Two players alternate removing 1, 2, or 3 stones. Whoever removes the last stone wins. You move first and both play perfectly. How many should you remove first to force a win?',
['1','2','3','There is no winning first move.'],0,
['Which small pile sizes are losing for the player whose turn it is?','Try leaving a multiple of four.'],
'Remove 1 to leave 20. If the opponent removes r stones, remove 4−r. Your paired turns remove four, leaving 16, 12, 8, 4, then 0 after your moves. Multiples of four are losing positions for the player to move.'),
puzzle('Tower of Hanoi','Patterns','Intermediate',
'Seven differently sized disks begin stacked smallest on top. Using three pegs, move the stack to another peg, moving one top disk at a time and never placing a larger disk on a smaller one. What is the minimum number of moves?',
['49','64','127','128'],2,
['Before moving the largest disk, move the six smaller ones away.','The recurrence is T(n) = 2T(n−1) + 1.'],
'To move n disks, move n−1 to the spare peg, move the largest, then move n−1 onto it. These steps are necessary and achievable. With T(0) = 0, T(n) = 2ⁿ−1, so T(7) = 127.'),
puzzle('The two-egg building','Strategy','Expert',
'You have two identical eggs and a 100-floor building. There is a threshold t in {0,…,100}: drops from floors at most t survive and higher drops break. An unbroken egg can be reused. What is the minimum worst-case number of drops needed to identify t?',
['10','14','20','50'],1,
['After the first egg breaks, you must search sequentially with the second.','Use decreasing jumps: m, then m−1, then m−2.'],
'With m drops and two eggs, the maximum searchable floor count is m+(m−1)+…+1 = m(m+1)/2. Thirteen cover only 91; fourteen cover 105. Drop first at 14, then 27, 39, 50, 60, 69, 77, 84, 90, 95, 99, and 100 as needed. After a break, test the skipped floors in order with the second egg, within a total budget of 14.'),
puzzle('The blue-eyed island','Deduction','Expert',
'Exactly 100 islanders have blue eyes; the others have brown eyes. Everyone is a perfect logician, sees everyone else’s eyes but cannot learn their own except by reasoning, and knows these rules. Nobody communicates eye information. Anyone who deduces they have blue eyes must leave at the next midnight. Before the first midnight, a visitor publicly announces, “At least one of you has blue eyes.” What happens?',
['All blue-eyed islanders leave at the first midnight.','One leaves each night.','All 100 blue-eyed islanders leave at the 100th midnight.','Nobody ever leaves.'],2,
['Begin with a hypothetical island containing just one blue-eyed person.','If n−1 people would leave on night n−1, what does their staying reveal?'],
'With one blue-eyed person, they see none and leave on night 1. With two, each waits for the other to leave on night 1; when neither does, both leave on night 2. Inductively, with n, everyone sees n−1 and waits for night n−1. No departure proves their own eyes are blue, so all n leave on night n. The public announcement establishes the necessary common knowledge.'),
puzzle('The hat line','Information','Expert',
'100 prisoners stand in a line wearing black or white hats. Each sees only the hats ahead. Starting from the back, each must say exactly “black” or “white” once as their guess; everyone hears prior guesses. No other signals are allowed. They may agree on a strategy beforehand. What is the largest number of correct guesses they can guarantee?',
['50','98','99','100'],2,
['The first speaker can encode information instead of identifying their own hat.','Use the parity of the black hats they see.'],
'The back prisoner says black for an odd number of black hats ahead and white for even. Each subsequent prisoner compares that parity with visible hats and the already deduced hats behind to determine their own. All 99 following prisoners are correct. The first prisoner cannot see their own hat, so no strategy guarantees that guess too.'),
puzzle('The unexpected ace','Probability','Intermediate',
'Two distinct cards are drawn uniformly without replacement from a standard 52-card deck. You are told that at least one is an ace, with no further selection rule. What is the probability both are aces?',
['1/13','1/17','1/33','1/221'],2,
['Count unordered two-card hands containing at least one ace.','There are 4×48 hands with exactly one ace and 6 with two.'],
'There are C(4,2) = 6 two-ace hands and 4×48 = 192 exactly-one-ace hands. Conditioning on at least one ace leaves 198 equally likely hands, so the probability is 6/198 = 1/33.'),
puzzle('The hundred prisoners','Probability','Expert',
'100 boxes contain a uniformly random permutation of numbers 1–100. Prisoner i may open at most 50 boxes and must find number i. Boxes are closed afterward, with no changes or communication between visits. They agree beforehand to start at box i, then repeatedly open the box numbered by the previous slip. Everyone succeeds exactly when the permutation’s longest cycle has length at most 50. What is their approximate chance of all succeeding?',
['Less than 0.001%','About 1%','About 31%','About 50%'],2,
['Cycles longer than 50 cannot coexist in a permutation of 100 items.','For k > 50, the probability of a k-cycle is 1/k.'],
'Failure occurs if a cycle has length 51 through 100. These events are mutually exclusive, and a random permutation has a k-cycle with probability 1/k when k > 50. Therefore success is 1 − (1/51 + … + 1/100) ≈ 0.31183, or 31.18%.'),
puzzle('Cheryl’s birthday','Deduction','Expert',
'Cheryl’s possible birthdays are May 15, 16, 19; June 17, 18; July 14, 16; August 14, 15, 17. Albert knows only the month; Bernard knows only the day. Albert: “I do not know the birthday, but I know Bernard does not know.” Bernard: “At first I did not know, but now I know.” Albert: “Then I know too.” What is the birthday?',
['July 16','August 15','June 17','May 19'],0,
['Days 18 and 19 each appear only once. What months can Albert rule out?','After May and June are eliminated, apply Bernard’s new certainty, then Albert’s.'],
'Albert’s certainty excludes May and June, which contain uniquely identifying days 19 and 18. Remaining dates are July 14/16 and August 14/15/17. Bernard now knows, so the day is not 14. This leaves July 16 and August 15/17. Albert can now know only if his month is July. The birthday is July 16.'),
]
for index, item in enumerate(PUZZLES, 1):
    item['id'] = index
